const websiteData = {
    boardup_com: {
        commonSecClass: "py-5 bg-background",
        heading_class: null,
        ulClass: "right-arrow count-2",
        btnClasses: "btn-website1",
        imgBox: "image-box",
        rowClass: "row align-items-center",
        imgCol: "col-md-6",
        contCol: "col-md-6",
    },
    aimright_com: {
        commonSecClass: "common-sec-website2",
        heading_class: "heading-website2",
        ulClass: "ul-class-website2",
        btnClasses: "btn-website2",
        imgBox: "img-box-website2",
        rowClass: "row-class-website2",
        imgCol: "img-col-website2",
        contCol: "cont-col-website2",
    },
    arearugcleaning_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "checked",
        btnClasses: "btn common-btn cta-phone",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    coloradowaterrestoration_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "cta-phone common-btn btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 mb-4 mb-md-0",
        contCol: "col-lg-6",
    },
    asg_security_com: {
        commonSecClass: "common-sec",
        heading_class: "",
        ulClass: "check-square",
        btnClasses: "btn common-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
     northtxgen_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "btn common-btn mt-3",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    rhinohomecare_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "btn common-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    specialtouchrestoration_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "common btn m-2",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    easiercomms_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "custom-btn secondary-bg",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    dalworthrestoration_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "checked",
        btnClasses: "common btn m-2",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    panhandlecr_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "common btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    sentinelexteriors_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "custom-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    chenalpainting_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "custom-list",
        btnClasses: "common btn red",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    northeastbasements_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-mark",
        btnClasses: "btn common-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    restorationrenegades_com: {
        commonSecClass: "section-bg",
        heading_class: "section-heading",
        ulClass: "check-mark",
        btnClasses: "common-button",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    heartlandroofingandsiding_com: {
        commonSecClass: "section-bg",
        heading_class: "section-heading",
        ulClass: "check-mark",
        btnClasses: "theme-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    frontiergp_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "common btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    dryworxwaterproofing_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-mark",
        btnClasses: "btn common-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    teasdalefenton_dayton_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "custom-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    teasdalerugcleaning_com: {
        commonSecClass: "inner-page-section",
        heading_class: "section-heading",
        ulClass: "check-mark",
        btnClasses: "btn-with-left-bar",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    chenalrestoration_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "common btn red m-1",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 ",
        contCol: "col-lg-6",
    },
    ewingair_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "btn common-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 mb-4 mb-md-0",
        contCol: "col-lg-6",
    },
    riversidehac_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "angle-right",
        btnClasses: "cta-red common btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    valorjanitorial_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "checked",
        btnClasses: "custom-btn view-slide",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    anchorrestoration_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "common btn red",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    glhrco_com: {
        commonSecClass: "py-5",
        heading_class: "common-heading",
        ulClass: "angle-right",
        btnClasses: "btn common",
        imgBox: "image-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6 mb-4 mb-md-0",
        contCol: "col-lg-6",
    },
    bestcdrs_com: {
        commonSecClass: "py-5",
        heading_class: "common-heading",
        ulClass: "angle-right",
        btnClasses: "common btn",
        imgBox: "image-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    
    bockairconditioning_com: {
        commonSecClass: "area-padding-60 bg-light",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "btn common-btn bg-danger",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    jafrirugcleaning_com: {
        commonSecClass: "area-padding-60 bg-light",
        heading_class: "common-heading",
        ulClass: "checked",
        btnClasses: "custom-btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    dalworthrugcleaning_com: {
        commonSecClass: "section-bg",
        heading_class: "section-heading",
        ulClass: "check-square",
        btnClasses: "cta-contact common-btn btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    hydro_clean_net: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "check-square",
        btnClasses: "custom-btn red mt-4",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },
    servicemasterprofessionalrestoration_com: {
        commonSecClass: "common-sec",
        heading_class: "common-heading",
        ulClass: "angle-right",
        btnClasses: "cta-red common btn",
        imgBox: "img-box",
        rowClass: "row align-items-center",
        imgCol: "col-lg-6",
        contCol: "col-lg-6",
    },

    
    // Add more website configurations as needed
};
